Chore: Fix tests on SQLAlchemy 1.3, by skipping them
We don't know which circumstances cause this problem. SQLAlchemy 1.3 is
EOL anyway, so we don't care too much.

sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped
class RootStore->root, expression 'ItemStore' failed to locate a name
('ItemStore').