Dialect: Fix `get_pk_constraint` to return `list` instead of `set` type
The test suite of `meltano-tap-cratedb`, derived from the corresponding
PostgreSQL adapter, will process database introspection return values by
marshalling them to JSON. Because `get_pk_constraint` returns a `set`
type, that will fail.

    TypeError: Object of type set is not JSON serializable